# Generated by Django 4.1.3 on 2023-04-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='категория')),
                ('slug_category', models.SlugField(max_length=32, unique=True, verbose_name='url')),
                ('sort_order', models.IntegerField(verbose_name='очередность сортировки')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='подкатегория')),
                ('slug_subcategory', models.SlugField(max_length=64, unique=True, verbose_name='url')),
                ('sort_order', models.IntegerField(verbose_name='сортировка')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hubs.categories', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
