# Generated by Django 4.1.3 on 2023-04-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_alter_subcategories_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
