# Generated by Django 4.1.3 on 2023-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pic', verbose_name='profile_foto'),
        ),
    ]
